spring:
  application:
    name: quickbasket
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/quickbasket
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

quickcommerce:
  api:
    base-url: https://api.quickcommerceapi.com
    token: mock-bearer-token-12345
    active-provider: all

quickbasket:
  cache:
    ttl-seconds: 300
  providers:
    mock:
      enabled: true
      timeout-ms: 1500
    quickcommerce:
      enabled: false
      timeout-ms: 1500

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
